### ISSUE TITLE
Thanks and Reference

### ISSUE THREAD

**Issue by simlu** [davidbrewer/xmonad-ubuntu-conf#14]
Started my own repo recently: https://github.com/simlu/xmonad
I've tried to keep it a modular and put the user in charge of customization.

Just discovered this repo now and learned a lot already that I want to incorporate. Conversely I thought you might want to take a look at my repo as well!

Thanks again and I hope we can increase the amount of xmonad users drastically in the future!

**Comment by davidbrewer** [comment]
Thanks! Was interested to look at what you're doing (even if I am about six months late!). I like how your documentation is a bit more modular than mine.  :-)

I was especially interested to learn of Taffybar -- to be honest, this has been working for me for 5 or 6 years with very little modification and I haven't really kept up with what developments might have been happening in the Xmonad world. It seems like Taffybar might be a good replacement for both Xmobar and Stalonetray, and I dig simplicity, so I might have to look into a bit of a retool when time allows!
