### ISSUE TITLE
Does not start on 18.04

### ISSUE THREAD

**Issue by jl2035** [davidbrewer/xmonad-ubuntu-conf#19]
Should this work out-of-the-box? I have a fresh Ubuntu 18.04 installation and xmonad does not start properly. I only see the desktop background and a mouse. No status bar. Mod+shift+enter and Ctrl+Space don't do anything :(

**Comment by brownnrl** [comment]
Please note that I am not the repo owner, I have just been using it for my home computers for a while.

I did an upgrade from 16 to 18.04, and it does work for me.  I have another box I just did a fresh install of Ubuntu 18.04 on, and I am going to install xmonad with David's configuration as well.

I did have to ensure that the Xmonad is being started and that the relevant start up scripts are running.  So part of that might be piping some to some text files at select locations the results of the execution of the script [start-xmonad](https://github.com/davidbrewer/xmonad-ubuntu-conf/blob/master/start-xmonad).

This is executed after you have placed the [desktop file in the appropriate location](https://github.com/davidbrewer/xmonad-ubuntu-conf#install-customized-xmonad-session).

Could you elaborate on the steps you took to install it?

**Comment by jl2035** [comment]
Actually my installation is totally fucked up, so I don't think I'll have the time to debug this now. Closing.
