### ISSUE TITLE
Some steps in the installation script fail on Ubuntu 18.04

### ISSUE THREAD

**Issue by dnadales** [davidbrewer/xmonad-ubuntu-conf#21]
Thank you for taking the time to put this configuration and instructions together. 

I just wanted to mention that on Ubuntu 18.04 the following steps of the Xmonad installation script fail:

```text
Creating xmonad xsession configuration...
cp: cannot stat '/home/damian/.xmonad/xmonad.desktop': No such file or directory
chmod: cannot access '/usr/share/xsessions/xmonad.desktop': No such file or directory
```

**Comment by davidbrewer** [comment]
Apologies for a VERY slow reply. I'm not able to use this at work anymore so I can't give it the attention I once did!

I'm not able to reproduce this issue, but it looks like the installer was looking for the file `.xmonad/xmonad.desktop` in your home directory but didn't find it. Is it possible that you cloned this repository into a different location than `.xmonad` in your home directory?

**Comment by dnadales** [comment]
Hi David, thank you for your reply. 

> Is it possible that you cloned this repository into a different location than .xmonad in your home directory?

That's entirely possible :) I'll linking the directory where the scripts expect it. Thank you for your help!
