### ISSUE TITLE
Notes for ubuntu 20.04

### ISSUE THREAD

**Issue by hp77-creator** [davidbrewer/xmonad-ubuntu-conf#22]
As ubuntu has shifted its sole attention to ubuntu 20.xx, It will be better to update the repo with the guidance for that.

**Comment by davidbrewer** [comment]
I just pushed a few updates! There was very little change needed as far as I can tell. Please let me know if you encounter any specific problems with the configuration. Note that if you did a dist-upgrade to 20.04, you may need to take a step to replace the xsession file -- refer to this in the README: https://github.com/davidbrewer/xmonad-ubuntu-conf#oh-no-i-upgraded-ubuntu-and-everything-broke
